includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed. Leave a comment with 'ryu-recheck' to rerun a check. (Also 'recheck' is available.)
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
          branch: ^(master|stable/.*)$
        - event: change-restored
          branch: ^(master|stable/.*)$
        # Change "myvendor" below to your vendor's name to add a custom
        # recheck trigger that runs the check pipeline jobs when someone
        # adds a comment to a review that says "recheck $VENDOR".
        - event: comment-added
          branch: ^(master|stable/.*)$
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(ryu-recheck|recheck)\s*$
#        - event: comment-added
#          branch: ^(master|stable/.*)$
#          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( myvendor))\s*$
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

jobs:
  - name: ^.*$
    parameter-function: set_node_options_default_trusty
  - name: ^check-tempest-dsvm-ofagent.*$
    branch: ^(master).*$
    parameter-function: set_log_url
    success-pattern: http://180.37.183.32/ryuci/{build.parameters[LOG_PATH]}
    failure-pattern: http://180.37.183.32/ryuci/{build.parameters[LOG_PATH]}
  - name: ^check-tempest-dsvm-k-ofagent.*$
    branch: ^(stable/kilo).*$
    parameter-function: set_log_url
    success-pattern: http://180.37.183.32/ryuci/{build.parameters[LOG_PATH]}
    failure-pattern: http://180.37.183.32/ryuci/{build.parameters[LOG_PATH]}
  - name: ^(check-tempest-dsvm-j-ofagent|check-tempest-dsvm-ryuplugin).*$
    branch: ^(stable/juno).*$
    parameter-function: set_log_url
    success-pattern: http://180.37.183.32/ryuci/{build.parameters[LOG_PATH]}
    failure-pattern: http://180.37.183.32/ryuci/{build.parameters[LOG_PATH]}

projects:
  - name: openstack/neutron
    check:
      - check-tempest-dsvm-ofagent
      - check-tempest-dsvm-k-ofagent
      - check-tempest-dsvm-j-ofagent
      - check-tempest-dsvm-ryuplugin
  - name: stackforge/networking-ofagent
    check:
      - check-tempest-dsvm-ofagent
      - check-tempest-dsvm-k-ofagent
      - check-tempest-dsvm-j-ofagent
